/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import AccesoADatos.SocioData;
import Entidades.Socio;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alakyan
 */
public class VistaListaSocios extends javax.swing.JInternalFrame {
    SocioData socioData;
    ArrayList<Socio> socios;
    private DefaultTableModel modelo= new DefaultTableModel(){ 
    public boolean isCellEditable(int f,int c){
       
        return false;
        }
    };

    /**
     * Creates new form VistaListaSocios
     */
    public VistaListaSocios() {
        initComponents();
        jrb_Activos.setSelected(true);
        socioData=new SocioData();
        socios=new ArrayList<>();
        armarCabeceras();
        listaSocios();
        
    }
    
    private void armarCabeceras(){
        ArrayList<Object> filaCabecera = new ArrayList<>();
        modelo.addColumn("N° Socio");
        modelo.addColumn("DNI");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Edad");
        modelo.addColumn("Correo");
        modelo.addColumn("Telefono");
        modelo.addColumn("Activo");
        for(Object it: filaCabecera){
            modelo.addColumn(it);
        }
        jt_TablaSocios.setModel(modelo);
    }
    
    private void borrarFilas(){
        int filas=jt_TablaSocios.getRowCount()-1;        
        for (int f = filas; f >= 0; f--) {
            modelo.removeRow(f);
        }
    }
    private String siOno(boolean valor){
        if(valor){
            return "si";
        }else{
            return "no";
        }
    }
    
    private void listaSocios(){
        borrarFilas();
        
        socios=(ArrayList<Socio>) socioData.listarSocios();
        if(jrb_Activos.isSelected()){
        for(Socio s: socios){
        String estado=siOno(s.isEstado());
            if(s.isEstado()){
        modelo.addRow(new Object[]{s.getIdSocio(),s.getDni(),s.getNombre(),s.getApellido(),s.getEdad(),s.getCorreo(),s.getTelefono(),estado});
            }
        }
        }else{
            for(Socio s: socios){
        String estado=siOno(s.isEstado());
        modelo.addRow(new Object[]{s.getIdSocio(),s.getDni(),s.getNombre(),s.getApellido(),s.getEdad(),s.getCorreo(),s.getTelefono(),estado});
        }
        }
    }
    
    private void busqueda(){
        borrarFilas();
        
        if(jt_BuscarXNombre.getText().equalsIgnoreCase("")){
     listaSocios();
    }else{
        socios=(ArrayList<Socio>) socioData.listarSocios();
            for (Socio s: socios) {
                String estado=siOno(s.isEstado());
                if(s.getNombre().toLowerCase().contains(jt_BuscarXNombre.getText().toLowerCase()) && !jrb_Activos.isSelected()){
                    modelo.addRow(new Object[]{s.getIdSocio(),s.getDni(),s.getNombre(),s.getApellido(),s.getEdad(),s.getCorreo(),s.getTelefono(),estado});
                }else if(s.getNombre().toLowerCase().contains(jt_BuscarXNombre.getText().toLowerCase()) && jrb_Activos.isSelected() && jrb_Activos.isSelected()==s.isEstado()){
                    modelo.addRow(new Object[]{s.getIdSocio(),s.getDni(),s.getNombre(),s.getApellido(),s.getEdad(),s.getCorreo(),s.getTelefono(),estado});
                }
            }
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jt_TablaSocios = new javax.swing.JTable();
        jb_Salir = new javax.swing.JButton();
        jt_BuscarXNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jrb_Activos = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        jt_TablaSocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jt_TablaSocios);

        jb_Salir.setText("Salir");
        jb_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_SalirActionPerformed(evt);
            }
        });

        jt_BuscarXNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jt_BuscarXNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_BuscarXNombreKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("LISTA DE SOCIOS");

        jrb_Activos.setText("Solo Socios Activos");
        jrb_Activos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_ActivosActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jrb_Activos)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(260, 260, 260))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt_BuscarXNombre)
                        .addGap(95, 95, 95)
                        .addComponent(jb_Salir)
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_BuscarXNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_Salir)
                    .addComponent(jrb_Activos)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_SalirActionPerformed
    dispose(); 
    }//GEN-LAST:event_jb_SalirActionPerformed

    private void jt_BuscarXNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_BuscarXNombreKeyTyped
        busqueda();
    }//GEN-LAST:event_jt_BuscarXNombreKeyTyped

    private void jrb_ActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_ActivosActionPerformed
        busqueda();
        
        
    }//GEN-LAST:event_jrb_ActivosActionPerformed

    private void jt_BuscarXNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_BuscarXNombreKeyReleased
        busqueda();
    }//GEN-LAST:event_jt_BuscarXNombreKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_Salir;
    private javax.swing.JRadioButton jrb_Activos;
    private javax.swing.JTextField jt_BuscarXNombre;
    private javax.swing.JTable jt_TablaSocios;
    // End of variables declaration//GEN-END:variables
}
