/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import AccesoADatos.AsistenciaData;
import AccesoADatos.ClasesData;
import AccesoADatos.InscripcionData;
import AccesoADatos.MembresiaData;
import AccesoADatos.SocioData;
import Entidades.Asistencia;
import Entidades.Clase;
import Entidades.Membresia;
import Entidades.Socio;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author jose-garces
 */
public class VistaAsistencia extends javax.swing.JInternalFrame {
    AsistenciaData asistenciaData;
    InscripcionData inscripcionData;
    ClasesData claseData;
    SocioData socioData;
    MembresiaData membresiaData;
    List<Clase> clases;
    int claseA;
    int socioA;
    ArrayList<Socio> sociosInscriptos = null;
    
    /**
     * Creates new form VistaAsistencia
     */
    public VistaAsistencia() {
        initComponents();
        asistenciaData=new AsistenciaData();
        socioData=new SocioData();
        claseData=new ClasesData();
        inscripcionData=new InscripcionData();
        membresiaData=new MembresiaData();
        marcarFecha();
        actualizarMembresias();
        cargarCombo();
        cargaSocios();
    }

    
    
    
    private void cargarCombo() {
        jcb_ComboClase.removeAllItems();
        clases = claseData.listarClases();
        for (Clase clase : clases) {
            jcb_ComboClase.addItem(clase.toString());
        }
    }
        

    private void cargaSocios() {
        jcb_Socios.removeAllItems();
        String clasesSeleccionada = (String) jcb_ComboClase.getSelectedItem();
        
             
            if (clasesSeleccionada != null) {
                for (Clase clase: clases){
                    if (clase.toString().equals(clasesSeleccionada)){
                        claseA=clase.getIdClase();
                        break;
            }
        }
                List<Socio> sociosInscriptos = inscripcionData.listarSociosInscriptos(claseA);
                for (Socio socio:sociosInscriptos){
                    jcb_Socios.addItem(socio.toString());
                }
    }
            else{
                JOptionPane.showMessageDialog(this, "No se encontraron socios inscriptos para la clase");
            }
    }
    private void actualizarMembresias(){
        List<Socio> socios=socioData.listarSocios();
        for (Socio socio : socios) {
          socioData.membresiaActiva(socio.getIdSocio());  
        }
        
    }
    
    private void marcarFecha(){
        LocalDate hoy=LocalDate.now();
        jl_FechaHoy.setText(hoy.toString());
    }
    

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcb_ComboClase = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jcb_Socios = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jb_MarcarAsistencia = new javax.swing.JButton();
        jb_Salir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jl_FechaHoy = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Chilanka", 0, 24)); // NOI18N
        jLabel1.setText("Asistencia");

        jcb_ComboClase.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcb_ComboClaseItemStateChanged(evt);
            }
        });

        jLabel2.setText("Clase a Ingresar:");

        jLabel3.setText("Socio:");

        jb_MarcarAsistencia.setText("Marcar Asistencia");
        jb_MarcarAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_MarcarAsistenciaActionPerformed(evt);
            }
        });

        jb_Salir.setText("Salir");
        jb_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_SalirActionPerformed(evt);
            }
        });

        jLabel4.setText("Fecha");

        jl_FechaHoy.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jl_FechaHoy.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcb_Socios, 0, 576, Short.MAX_VALUE)
                    .addComponent(jcb_ComboClase, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addComponent(jl_FechaHoy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(284, 284, 284))
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jb_MarcarAsistencia)
                .addGap(83, 83, 83)
                .addComponent(jb_Salir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jl_FechaHoy)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_ComboClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_Socios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_MarcarAsistencia)
                    .addComponent(jb_Salir))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcb_ComboClaseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcb_ComboClaseItemStateChanged
        cargaSocios();
    }//GEN-LAST:event_jcb_ComboClaseItemStateChanged

    private void jb_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_SalirActionPerformed
        dispose();
    }//GEN-LAST:event_jb_SalirActionPerformed

    private void jb_MarcarAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_MarcarAsistenciaActionPerformed
   String socioSeleccionado =(String) jcb_Socios.getSelectedItem();
   if(socioSeleccionado==null){
       JOptionPane.showMessageDialog(this, "Seleccione un socio!");
       return;
   }
           Socio socioEncontrado =null;
           for(Socio socio: inscripcionData.listarSociosInscriptos(claseA)){
               if(socio.toString().equals(socioSeleccionado)){
                   socioEncontrado=socio;
                   socioA=socio.getIdSocio();
                  break;
               }
           }
           
           LocalDate hoy= LocalDate.now();
           
           
           ArrayList<Integer> presentes = (ArrayList<Integer>) asistenciaData.sociosIDPresentes(claseA, hoy);
           if (presentes==null){
               presentes=new ArrayList<>();
           }
           if(presentes.contains(socioA)){
               JOptionPane.showMessageDialog(this, "Socio ya dio el presente!");
              return;
           }  
           
           List<Membresia> membresia=membresiaData.listarMembresiasPorSocio(socioA);
           if(!membresia.isEmpty()){
               Membresia primerMembresia =membresia.get(0);
               membresiaData.usarMembresia(primerMembresia.getIdMembresia());
           }else{
               JOptionPane.showMessageDialog(this, "No tiene mas mebresias!");
               return;
           }
                          JOptionPane.showMessageDialog(this, "Asistencia marcada correctamente!");
           
           Asistencia asistencia = new Asistencia(socioEncontrado, claseData.buscarClase(claseA),hoy);
           asistenciaData.guardarAsistencia(asistencia);
    }//GEN-LAST:event_jb_MarcarAsistenciaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jb_MarcarAsistencia;
    private javax.swing.JButton jb_Salir;
    private javax.swing.JComboBox<String> jcb_ComboClase;
    private javax.swing.JComboBox<String> jcb_Socios;
    private javax.swing.JLabel jl_FechaHoy;
    // End of variables declaration//GEN-END:variables
}
